apiVersion: v1
kind: Service
metadata:
  name: nagp-rest-api-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    app: nagp-rest-api
